/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import java.util.ArrayList;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;


/**
 *
 * @author walee
 */
public class AdminAndraProjekt extends javax.swing.JFrame {
    
    private InfDB idb;
    private String InloggadAnvandare;
    

    /**
     * Creates new form AdminAndraProjekt
     */
    public AdminAndraProjekt(InfDB idb, String InloggadAnvandare) {
        this.idb = idb;
        this.InloggadAnvandare = InloggadAnvandare;
        initComponents();
        fyllComboBox();
        jLVemInlogg.setText(InloggadAnvandare);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLVemInlogg = new javax.swing.JLabel();
        jCBValjProjekt = new javax.swing.JComboBox<>();
        jLPidProjekt = new javax.swing.JLabel();
        jLProjektnamnProjekt = new javax.swing.JLabel();
        jLBeskrivningProjekt = new javax.swing.JLabel();
        jLStartdatumProjekt = new javax.swing.JLabel();
        jLSlutdatumProjekt = new javax.swing.JLabel();
        jLKostnadProjekt = new javax.swing.JLabel();
        jLStatusProjekt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLProjektchefProjekt = new javax.swing.JLabel();
        jLLandProjekt = new javax.swing.JLabel();
        jTFPidProjekt = new javax.swing.JTextField();
        jTFProjektnamnProjekt = new javax.swing.JTextField();
        jTFBeskrivningProjekt = new javax.swing.JTextField();
        jTFStartdatumProjekt = new javax.swing.JTextField();
        jTFSlutdatumProjekt = new javax.swing.JTextField();
        jTFKostnadProjekt = new javax.swing.JTextField();
        jTFStatusProjekt = new javax.swing.JTextField();
        jTFPrioritetProjekt = new javax.swing.JTextField();
        jTFProjektchefProjekt = new javax.swing.JTextField();
        jTFLandProjekt = new javax.swing.JTextField();
        jBAndraProjekt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Ändra Projekt");

        jLVemInlogg.setText("jLabel2");

        jCBValjProjekt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBValjProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBValjProjektActionPerformed(evt);
            }
        });

        jLPidProjekt.setText("Pid");

        jLProjektnamnProjekt.setText("Projektnamn");

        jLBeskrivningProjekt.setText("Beskrivning");

        jLStartdatumProjekt.setText("Startdatum");

        jLSlutdatumProjekt.setText("Slutdatum");

        jLKostnadProjekt.setText("Kostnad");

        jLStatusProjekt.setText("Status");

        jLabel2.setText("Prioritet");

        jLProjektchefProjekt.setText("Projektchef");

        jLLandProjekt.setText("Land");

        jTFPidProjekt.setText("jTextField1");

        jTFProjektnamnProjekt.setText("jTextField1");

        jTFBeskrivningProjekt.setText("jTextField1");

        jTFStartdatumProjekt.setText("jTextField1");

        jTFSlutdatumProjekt.setText("jTextField1");

        jTFKostnadProjekt.setText("jTextField1");

        jTFStatusProjekt.setText("jTextField1");

        jTFPrioritetProjekt.setText("jTextField1");

        jTFProjektchefProjekt.setText("jTextField1");

        jTFLandProjekt.setText("jTextField1");

        jBAndraProjekt.setText("Ändra");
        jBAndraProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAndraProjektActionPerformed(evt);
            }
        });

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLLandProjekt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLProjektchefProjekt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLPidProjekt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLStatusProjekt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLKostnadProjekt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLSlutdatumProjekt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLStartdatumProjekt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLBeskrivningProjekt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLProjektnamnProjekt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTFPidProjekt)
                            .addComponent(jTFProjektnamnProjekt)
                            .addComponent(jTFBeskrivningProjekt)
                            .addComponent(jTFStartdatumProjekt)
                            .addComponent(jTFSlutdatumProjekt)
                            .addComponent(jTFKostnadProjekt)
                            .addComponent(jTFStatusProjekt)
                            .addComponent(jTFPrioritetProjekt)
                            .addComponent(jTFProjektchefProjekt)
                            .addComponent(jTFLandProjekt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(jLVemInlogg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jCBValjProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jBAndraProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLVemInlogg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBValjProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPidProjekt)
                    .addComponent(jTFPidProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLProjektnamnProjekt)
                    .addComponent(jTFProjektnamnProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBeskrivningProjekt)
                    .addComponent(jTFBeskrivningProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStartdatumProjekt)
                    .addComponent(jTFStartdatumProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSlutdatumProjekt)
                    .addComponent(jTFSlutdatumProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLKostnadProjekt)
                    .addComponent(jTFKostnadProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStatusProjekt)
                    .addComponent(jTFStatusProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFPrioritetProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLProjektchefProjekt)
                    .addComponent(jTFProjektchefProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLLandProjekt)
                    .addComponent(jTFLandProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBAndraProjekt)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fyllComboBox() {
        jCBValjProjekt.removeAllItems();
    try {
        String sql = "SELECT projektnamn FROM projekt";
        ArrayList<String> ettProjekt = idb.fetchColumn(sql);

        if (ettProjekt != null) {
            for (String projekt : ettProjekt) {
                jCBValjProjekt.addItem(projekt);
            }
        } else {
            System.out.println("Inga projekt hittades.");
        }
    } catch (InfException e) {
        System.out.println("Ett fel uppstod vid hämtning av projektnamn.");
    }
}
    
    
    
    private void jCBValjProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBValjProjektActionPerformed
        
         String valtProjekt = (String) jCBValjProjekt.getSelectedItem();
    if (valtProjekt != null) {
        try {
            String sql = "SELECT * FROM projekt WHERE projektnamn = '" + valtProjekt + "'";
            HashMap<String, String> projekt = idb.fetchRow(sql);
            
            if (projekt != null) {
                jTFPidProjekt.setText(projekt.get("pid"));
                jTFProjektnamnProjekt.setText(projekt.get("projektnamn"));
                jTFBeskrivningProjekt.setText(projekt.get("beskrivning"));
                jTFStartdatumProjekt.setText(projekt.get("startdatum"));
                jTFSlutdatumProjekt.setText(projekt.get("slutdatum"));
                jTFKostnadProjekt.setText(projekt.get("kostnad"));
                jTFStatusProjekt.setText(projekt.get("status"));
                jTFPrioritetProjekt.setText(projekt.get("prioritet"));
                jTFProjektchefProjekt.setText(projekt.get("projektchef"));
                jTFLandProjekt.setText(projekt.get("land"));
                
                
            } else {
                System.out.println("Kunde inte hitta projekt.");
            }
        } catch (InfException e) {
            System.out.println("Ett fel uppstod vid hämtning av projektdetaljer.");
        }
    }
        
    }//GEN-LAST:event_jCBValjProjektActionPerformed

    private void jBAndraProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAndraProjektActionPerformed
        
    String pid = jTFPidProjekt.getText();
    String projektnamn = jTFProjektnamnProjekt.getText();
    String beskrivning = jTFBeskrivningProjekt.getText();
    String startdatum = jTFStartdatumProjekt.getText();
    String slutdatum = jTFSlutdatumProjekt.getText();
    String kostnad = jTFKostnadProjekt.getText();
    String status = jTFStatusProjekt.getText();
    String prioritet = jTFPrioritetProjekt.getText();
    String projektchef = jTFProjektchefProjekt.getText();
    String land = jTFLandProjekt.getText();

    try {
        // Uppdatera databasen med de nya värdena
        String sqlAndring = "UPDATE projekt SET projektnamn = '" + projektnamn + "', beskrivning = '" + beskrivning + "', startdatum = '" + startdatum + "', slutdatum = '" + slutdatum + "', kostnad = '" + kostnad + "', status = '" + status +  "', prioritet = '" + prioritet +  "', projektchef = '" + projektchef +  "', land = '" + land + "' WHERE pid = '" + pid + "'";
        idb.update(sqlAndring);
        
        // Visa en bekräftelse att ändringarna har genomförts
        System.out.println("Ändringar har genomförts.");
    } catch (InfException e) {
        // Visa felmeddelande om något går fel vid uppdateringen
        System.out.println("Ett fel uppstod. Ändringar kunde inte genomföras.");
        e.printStackTrace();
    }
        
    }//GEN-LAST:event_jBAndraProjektActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new AdminProjekt(idb, InloggadAnvandare).setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAndraProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAndraProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAndraProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAndraProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AdminAndraProjekt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAndraProjekt;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBValjProjekt;
    private javax.swing.JLabel jLBeskrivningProjekt;
    private javax.swing.JLabel jLKostnadProjekt;
    private javax.swing.JLabel jLLandProjekt;
    private javax.swing.JLabel jLPidProjekt;
    private javax.swing.JLabel jLProjektchefProjekt;
    private javax.swing.JLabel jLProjektnamnProjekt;
    private javax.swing.JLabel jLSlutdatumProjekt;
    private javax.swing.JLabel jLStartdatumProjekt;
    private javax.swing.JLabel jLStatusProjekt;
    private javax.swing.JLabel jLVemInlogg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTFBeskrivningProjekt;
    private javax.swing.JTextField jTFKostnadProjekt;
    private javax.swing.JTextField jTFLandProjekt;
    private javax.swing.JTextField jTFPidProjekt;
    private javax.swing.JTextField jTFPrioritetProjekt;
    private javax.swing.JTextField jTFProjektchefProjekt;
    private javax.swing.JTextField jTFProjektnamnProjekt;
    private javax.swing.JTextField jTFSlutdatumProjekt;
    private javax.swing.JTextField jTFStartdatumProjekt;
    private javax.swing.JTextField jTFStatusProjekt;
    // End of variables declaration//GEN-END:variables
}
