/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author User
 */
public class AdminMeny extends javax.swing.JFrame {

    private InfDB idb;
    private String InloggadAnvandare;
    
    /**
     * Creates new form Meny
     */
    public AdminMeny(InfDB idb, String InloggadAnvandare) {
        this.idb = idb;
        this.InloggadAnvandare = InloggadAnvandare;
        initComponents();
        lblInloggadAnvandare.setText(InloggadAnvandare);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInloggadAnvandare = new javax.swing.JLabel();
        aB1 = new javax.swing.JButton();
        pA1 = new javax.swing.JButton();
        aA1 = new javax.swing.JButton();
        txtAdminMeny = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInloggadAnvandare.setText("JLabel");

        aB1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        aB1.setText("Anställda");
        aB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aB1ActionPerformed(evt);
            }
        });

        pA1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pA1.setText("Projekt");
        pA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pA1ActionPerformed(evt);
            }
        });

        aA1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        aA1.setText("Avdelningar");
        aA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aA1ActionPerformed(evt);
            }
        });

        txtAdminMeny.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtAdminMeny.setText("Admin meny");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lblInloggadAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aB1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pA1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aA1)))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtAdminMeny, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtAdminMeny)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInloggadAnvandare)
                .addGap(18, 18, 18)
                .addComponent(aB1)
                .addGap(18, 18, 18)
                .addComponent(pA1)
                .addGap(18, 18, 18)
                .addComponent(aA1)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aB1ActionPerformed
        new Anstallda(idb, InloggadAnvandare).setVisible(true);
                this.setVisible(false);
     

    }//GEN-LAST:event_aB1ActionPerformed

    private void aA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aA1ActionPerformed
       new AdminAvdelning(idb, InloggadAnvandare).setVisible(true);
                this.setVisible(false);
     
    }//GEN-LAST:event_aA1ActionPerformed

    private void pA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pA1ActionPerformed
       new AdminProjekt(idb, InloggadAnvandare).setVisible(true);
       this.setVisible(false);
     
    }//GEN-LAST:event_pA1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AdminMeny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aA1;
    private javax.swing.JButton aB1;
    private javax.swing.JLabel lblInloggadAnvandare;
    private javax.swing.JButton pA1;
    private javax.swing.JLabel txtAdminMeny;
    // End of variables declaration//GEN-END:variables
}
//HEHEJH
