/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
import java.util.ArrayList;
/**
 *
 * @author walee
 */
public class AndraUppgifterAvdelning extends javax.swing.JFrame {
    private InfDB idb;
    private String InloggadAnvandare;
    /**
     * Creates new form AndraUppgifterAvdelning
     */
    public AndraUppgifterAvdelning(InfDB idb, String InloggadAnvandare) {
        this.idb = idb;
        initComponents();
        fyllComboBox();
        jLVemInlogg.setText(InloggadAnvandare);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLAndraUppgifter = new javax.swing.JLabel();
        jLVemInlogg = new javax.swing.JLabel();
        jLAvdid = new javax.swing.JLabel();
        jLNamnAvdelning = new javax.swing.JLabel();
        jLBeskrivningAvdelning = new javax.swing.JLabel();
        jLAdressAvdelning = new javax.swing.JLabel();
        jLEpostAvdelning = new javax.swing.JLabel();
        jLStadAvdelning = new javax.swing.JLabel();
        jLChefAvdelning = new javax.swing.JLabel();
        jTFAvdidAvdelning = new javax.swing.JTextField();
        jTFNamnAvdelning = new javax.swing.JTextField();
        jTFBeskrivningAvdelning = new javax.swing.JTextField();
        jTFAdressAvdelning = new javax.swing.JTextField();
        jTFEpostAvdelning = new javax.swing.JTextField();
        jTFStadAvdelning = new javax.swing.JTextField();
        jTFChefAvdelning = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCBValjAvdelning = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLTelefonAvdelning = new javax.swing.JLabel();
        jTFTelefonAvdelning = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLAndraUppgifter.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLAndraUppgifter.setText("Ändra Uppgifter");

        jLVemInlogg.setText("jLabel2");

        jLAvdid.setText("Avdid");

        jLNamnAvdelning.setText("Namn");

        jLBeskrivningAvdelning.setText("Beskrivning");

        jLAdressAvdelning.setText("Adress");

        jLEpostAvdelning.setText("Epost");

        jLStadAvdelning.setText("Stad");

        jLChefAvdelning.setText("Chef");

        jTFAvdidAvdelning.setText("jTextField1");

        jTFNamnAvdelning.setText("jTextField2");

        jTFBeskrivningAvdelning.setText("jTextField3");

        jTFAdressAvdelning.setText("jTextField4");

        jTFEpostAvdelning.setText("jTextField5");

        jTFStadAvdelning.setText("jTextField6");

        jTFChefAvdelning.setText("jTextField7");

        jButton1.setText("Avbryt");

        jButton2.setText("Ändra");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCBValjAvdelning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBValjAvdelning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBValjAvdelningActionPerformed(evt);
            }
        });

        jButton3.setText("Tillbaka");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLTelefonAvdelning.setText("Telefon");

        jTFTelefonAvdelning.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(169, 169, 169)
                                    .addComponent(jLVemInlogg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(114, 114, 114)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCBValjAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLAndraUppgifter))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLBeskrivningAvdelning)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jTFAdressAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTFBeskrivningAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLChefAvdelning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLStadAvdelning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLAdressAvdelning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(jLAvdid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLNamnAvdelning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFStadAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFChefAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFNamnAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFAvdidAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLTelefonAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTFTelefonAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLEpostAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTFEpostAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAndraUppgifter)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLVemInlogg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBValjAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAvdid)
                    .addComponent(jTFAvdidAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNamnAvdelning)
                    .addComponent(jTFNamnAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLBeskrivningAvdelning)
                    .addComponent(jTFBeskrivningAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAdressAvdelning)
                    .addComponent(jTFAdressAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEpostAvdelning)
                    .addComponent(jTFEpostAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTelefonAvdelning)
                    .addComponent(jTFTelefonAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStadAvdelning)
                    .addComponent(jTFStadAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLChefAvdelning)
                    .addComponent(jTFChefAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fyllComboBox() {
        jCBValjAvdelning.removeAllItems();
    try {
        String query = "SELECT namn FROM avdelning";
        ArrayList<String> avdelningar = idb.fetchColumn(query);

        if (avdelningar != null) {
            for (String avdelning : avdelningar) {
                jCBValjAvdelning.addItem(avdelning);
            }
        } else {
            System.out.println("Inga avdelningar hittades.");
        }
    } catch (InfException e) {
        System.out.println("Ett fel uppstod vid hämtning av avdelningsnamn.");
    }
}
    
    private void jCBValjAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBValjAvdelningActionPerformed
   
        String valtNamn = (String) jCBValjAvdelning.getSelectedItem();
    if (valtNamn != null) {
        try {
            String query = "SELECT * FROM avdelning WHERE namn = '" + valtNamn + "'";
            HashMap<String, String> avdelning = idb.fetchRow(query);

            if (avdelning != null) {
                jTFAvdidAvdelning.setText(avdelning.get("avdid"));
                jTFNamnAvdelning.setText(avdelning.get("namn"));
                jTFBeskrivningAvdelning.setText(avdelning.get("beskrivning"));
                jTFAdressAvdelning.setText(avdelning.get("adress"));
                jTFEpostAvdelning.setText(avdelning.get("epost"));
                jTFTelefonAvdelning.setText(avdelning.get("telefon"));
                jTFStadAvdelning.setText(avdelning.get("stad"));
                jTFChefAvdelning.setText(avdelning.get("chef"));
            } else {
                System.out.println("Kunde inte hitta avdelningen.");
            }
        } catch (InfException e) {
            System.out.println("Ett fel uppstod vid hämtning av avdelningsdetaljer.");
        }
    }

    }//GEN-LAST:event_jCBValjAvdelningActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
    String avdid = jTFAvdidAvdelning.getText();
    String namn = jTFNamnAvdelning.getText();
    String beskrivning = jTFBeskrivningAvdelning.getText();
    String adress = jTFAdressAvdelning.getText();
    String epost = jTFEpostAvdelning.getText();
    String telefon = jTFTelefonAvdelning.getText();
    String stad = jTFStadAvdelning.getText();
    String chef = jTFChefAvdelning.getText();

    try {
        // Uppdatera databasen med de nya värdena
String sqlAndring = "UPDATE avdelning SET namn = '" + namn + "', beskrivning = '" + beskrivning + "', adress = '" + adress + "', epost = '" + epost + "', telefon = '" + telefon + "', stad = '" + stad + "', chef = NULL WHERE avdid = '" + avdid + "'";
        idb.update(sqlAndring);
        
        // Visa en bekräftelse att ändringarna har genomförts
        System.out.println("Ändringar har genomförts.");
    } catch (InfException e) {
        // Visa felmeddelande om något går fel vid uppdateringen
        System.out.println("Ett fel uppstod. Ändringar kunde inte genomföras.");
        e.printStackTrace();
    }
  

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      new AdminMeny(idb, InloggadAnvandare).setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraUppgifterAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraUppgifterAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraUppgifterAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraUppgifterAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new AndraUppgifterAvdelning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCBValjAvdelning;
    private javax.swing.JLabel jLAdressAvdelning;
    private javax.swing.JLabel jLAndraUppgifter;
    private javax.swing.JLabel jLAvdid;
    private javax.swing.JLabel jLBeskrivningAvdelning;
    private javax.swing.JLabel jLChefAvdelning;
    private javax.swing.JLabel jLEpostAvdelning;
    private javax.swing.JLabel jLNamnAvdelning;
    private javax.swing.JLabel jLStadAvdelning;
    private javax.swing.JLabel jLTelefonAvdelning;
    private javax.swing.JLabel jLVemInlogg;
    private javax.swing.JTextField jTFAdressAvdelning;
    private javax.swing.JTextField jTFAvdidAvdelning;
    private javax.swing.JTextField jTFBeskrivningAvdelning;
    private javax.swing.JTextField jTFChefAvdelning;
    private javax.swing.JTextField jTFEpostAvdelning;
    private javax.swing.JTextField jTFNamnAvdelning;
    private javax.swing.JTextField jTFStadAvdelning;
    private javax.swing.JTextField jTFTelefonAvdelning;
    // End of variables declaration//GEN-END:variables
}
